import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/ui/navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative font-quicksand tracking-tight">
        <div>{children}</div>
      </body>
    </html>
  );
}
