import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative font-quicksand tracking-tight">
        <div>{children}</div>
      </body>
    </html>
  );
}

/*<nav className="fixed bg-primary text-accent z-10 text-xl font-semibold px-4 left-0 right-0 top-0 bg-transparent backdrop-blur-sm   flex items-center justify-between mx-auto">
<p>Bliss Hotel</p> 
<Image
  src={"./logo.svg"}
  width={50}
  height={50}
  alt="Logo"
  className=""
/>
<p>Book a Room</p>
</nav>*/
